### ISSUE TITLE
Crashing after a ~week of usage

### ISSUE THREAD

**Issue by bustedbunny** [lukaslangrock/ShutdownTimerClassic#35]
After about a week  of usage app starts to crash. Windows restart does not help.
Only full reinstall of app helps.

Happens very consistently on my side. Already reinstalled about 3 or 4 times because of that.

```
ShutdownTimerClassic@1.2.3 experienced a critical exception.
The following data includes information about your system, the exception and the internal state of the application at the time of the exception. You may remove certain information (like your username which may be included in the log) to protect your privacy.
Please open an issue on https://github.com/lukaslangrock/ShutdownTimerClassic and include the contents of this log file to help identify and fix the issue.


---- Process Info ----
PID: 16392
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 9
Responding: True
HasExited: False
StartTime: 02.06.2023 22:44:41
PeakWorkingSet64: 21,4MB (22478848byte)
WorkingSet64: 21,4MB (22478848byte)
PeakWorkingSet64: 21,4MB (22478848byte)
PrivateMemorySize64: 67,9MB (71176192byte)
VirtualMemorySize64: 268,7MB (281731072byte)
PeakVirtualMemorySize64: 269MB (282058752byte)
PagedSystemMemorySize64: 443,6KB (454288byte)
NonpagedSystemMemorySize64: 21KB (21512byte)
PagedMemorySize64: 67,9MB (71176192byte)
PeakPagedMemorySize64: 67,9MB (71176192byte)
UserProcessorTime: 00:00:00.0156250
TotalProcessorTime: 00:00:00.0156250
PrivilegedProcessorTime: 00:00:00


---- Application Info ----
Product Name: ShutdownTimerClassic
Product Version: 1.2.3.0
Current Culture: ru-KZ
Executable Path: C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.3.0_x64__jnfph5tq58r4j\ShutdownTimer\ShutdownTimerClassic.exe
MD5 Checksum: f755519e89e2e543ed11f113634d6e20


---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.22621.0
Runtime Version: 4.0.30319.42000
System Uptime: 57934031
Machine Name: BUSTEDBUNNY-PC
Processor Count: 16
Shutdown Started: False


---- Exception ----
Type: UnhandledException
Message: Object reference not set to an instance of an object.
Stack Trace:
    at ShutdownTimer.Helpers.SettingsProvider.CheckSettings()
   at ShutdownTimer.Helpers.SettingsProvider.Load()
   at ShutdownTimer.Program.Main(String[] args)


---- Internal Event Log ----
[Settings] Checking settings object
[Settings] Loading settings.json
[Settings] Loading settings...
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs


---- End of Log ----
```

**Comment by lukaslangrock** [comment]
Thanks for the report, and sorry for the **laaaate** reply. This problem is actually known and as you noticed, only reinstalling the app helps. Further discussion and updated will be posted in https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30 once I get back to work on this project again. Thanks again ^^
